databases:
  - name: oakley_trails
    databaseName: oakley_trails
    user: oakley_trails
    plan: free

services:
  - type: web
    name: oakley_trails
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oakley_trails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default